#!/usr/bin/env node
// 04-emit-ww.mjs
// Combine parsed.json + ai-cache.json into vocabulary-quiz/ww3000-data.js.
// Every WW word is emitted; CSV cnRaw is the guaranteed fallback for any
// word whose cache entry lacks definitionCn. Appends a slashed-id and
// review-plan migration block (same shape as life-basics-data.js).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CLEAN = join(__dirname, '..', 'data', 'clean');
const CACHE_PATH = join(__dirname, '..', '..', 'life-vocab-pipeline', 'data', 'clean', 'ai-cache.json');
const OUTPUT = join(__dirname, '..', '..', '..', 'vocabulary-quiz', 'ww3000-data.js');

const groups = JSON.parse(readFileSync(join(CLEAN, 'parsed.json'), 'utf8'));
const cache = existsSync(CACHE_PATH) ? JSON.parse(readFileSync(CACHE_PATH, 'utf8')) : {};

function js(s) { return JSON.stringify(s == null ? '' : String(s)); }

// Group by book first
const bookMap = new Map();
for (const g of groups) {
  if (!bookMap.has(g.book)) bookMap.set(g.book, new Map());
  bookMap.get(g.book).set(g.lesson, g.words);
}

const books = [];
let dropped = 0;
const droppedSamples = [];
for (const bookNum of [...bookMap.keys()].sort((a, b) => a - b)) {
  const bookId = `book-${bookNum}`;
  const lessonMap = bookMap.get(bookNum);
  const lessons = [];
  for (const lessonNum of [...lessonMap.keys()].sort((a, b) => a - b)) {
    const items = [];
    for (const raw of lessonMap.get(lessonNum)) {
      const ai = cache[raw.word];
      const definitionCn = (ai && ai.definitionCn) || raw.cnRaw || '';
      if (!definitionCn) {
        dropped++;
        if (droppedSamples.length < 15) droppedSamples.push(raw.word);
        continue;
      }
      items.push({
        word: raw.word,
        pos: (ai && ai.partOfSpeech) || '',
        phonetic: (ai && ai.phonetic) || '',
        definitionCn,
        definitionEn: (ai && ai.definitionEn) || '',
        cnRaw: raw.cnRaw || '',
      });
    }
    lessons.push({
      id: `${bookId}-lesson-${lessonNum}`,
      lesson: lessonNum,
      name: `Lesson ${lessonNum}`,
      items,
    });
  }
  books.push({
    id: bookId,
    grade: bookNum,
    label: `Book ${bookNum}`,
    name: `Book ${bookNum} · Grade ${bookNum}`,
    lessons,
  });
}

let body = '';
body += '// WW3000 vocabulary (Books 5-10) — generated by tools/ww3000-pipeline/04-emit-ww.mjs\n';
body += '// Source: busiyiworld/maimemo-export + Gemini enhanceWord enrichment.\n';
body += '// DO NOT edit by hand; rerun the pipeline instead.\n';
body += '(function () {\n';
body += '  function w(word, pos, phon, cn, en, cnRaw, bookId, lessonId) {\n';
body += '    return { word: word, pos: pos, phonetic: phon || "", definitionCn: cn, definitionEn: en || "", cnRaw: cnRaw || "", bookId: bookId, lessonId: lessonId };\n';
body += '  }\n\n';
body += '  var books = [\n';
for (const b of books) {
  body += '    {\n';
  body += `      id: ${js(b.id)},\n`;
  body += `      grade: ${b.grade},\n`;
  body += `      label: ${js(b.label)},\n`;
  body += `      name: ${js(b.name)},\n`;
  body += '      lessons: [\n';
  b.lessons.forEach((ls, idx) => {
    body += '        {\n';
    body += `          id: ${js(ls.id)},\n`;
    body += `          lesson: ${ls.lesson},\n`;
    body += `          name: ${js(ls.name)},\n`;
    body += '          items: [\n';
    ls.items.forEach((it, j) => {
      const last = j === ls.items.length - 1;
      body += `            w(${js(it.word)}, ${js(it.pos)}, ${js(it.phonetic)}, ${js(it.definitionCn)}, ${js(it.definitionEn)}, ${js(it.cnRaw)}, ${js(b.id)}, ${js(ls.id)})${last ? '' : ','}\n`;
    });
    body += '          ]\n';
    body += `        }${idx === b.lessons.length - 1 ? '' : ','}\n`;
  });
  body += '      ]\n';
  body += `    }${b === books[books.length - 1] ? '' : ','}\n`;
}
body += '  ];\n\n';

body += `  var lessons = [];
  var flat = [];
  books.forEach(function (book) {
    book.lessons.forEach(function (ls) {
      lessons.push({
        id: ls.id,
        bookId: book.id,
        bookLabel: book.label,
        grade: book.grade,
        lesson: ls.lesson,
        name: ls.name,
        items: ls.items
      });
      ls.items.forEach(function (item, idx) {
        flat.push(Object.assign({
          id: ls.id + '-' + (idx + 1),
          bookId: book.id,
          bookLabel: book.label,
          grade: book.grade,
          lessonId: ls.id,
          lessonNumber: ls.lesson,
          level: 'WW3000 Book ' + book.grade
        }, item));
      });
    });
  });

  // -- Migration A: ww3000_slashed records keyed by old id.
  try {
    var SLASHED_KEY = 'ww3000_slashed';
    var raw = localStorage.getItem(SLASHED_KEY);
    if (raw) {
      var slashed = JSON.parse(raw);
      var changed = false;
      var byWord = {};
      flat.forEach(function (it) { byWord[it.word.toLowerCase()] = it; });
      Object.keys(slashed).forEach(function (oldId) {
        var rec = slashed[oldId];
        if (!rec) return;
        var hit = byWord[String(rec.word || '').toLowerCase()];
        if (!hit) return;
        if (oldId !== hit.id) {
          slashed[hit.id] = Object.assign({}, rec, {
            id: hit.id,
            bookId: hit.bookId,
            lessonId: hit.lessonId,
            definitionCn: hit.definitionCn,
            definitionEn: hit.definitionEn
          });
          delete slashed[oldId];
          changed = true;
        }
      });
      if (changed) localStorage.setItem(SLASHED_KEY, JSON.stringify(slashed));
    }
  } catch (e) { /* ignore */ }

  // -- Migration B: review plan + word stats keyed by ww:<lessonId>::word.
  (function migrateKeyspace(storageKey) {
    try {
      var raw = localStorage.getItem(storageKey);
      if (!raw) return;
      var obj = JSON.parse(raw);
      if (!obj || typeof obj !== 'object') return;
      var changed = false;
      var wordToLesson = {};
      flat.forEach(function (it) { wordToLesson[it.word.toLowerCase()] = it.lessonId; });
      Object.keys(obj).forEach(function (key) {
        if (key.indexOf('ww:') !== 0) return;
        var parts = key.split('::');
        if (parts.length < 2) return;
        var wordPart = parts.slice(1).join('::').toLowerCase();
        var hitLesson = wordToLesson[wordPart];
        if (!hitLesson) return;
        var desiredKey = 'ww:' + hitLesson + '::' + wordPart;
        if (key !== desiredKey && !obj[desiredKey]) {
          obj[desiredKey] = obj[key];
          if (obj[desiredKey] && typeof obj[desiredKey] === 'object') {
            obj[desiredKey].categoryId = 'ww:' + hitLesson;
          }
          delete obj[key];
          changed = true;
        }
      });
      if (changed) localStorage.setItem(storageKey, JSON.stringify(obj));
    } catch (e) { /* ignore */ }
  })('vocab_quiz_review_plan');

  (function migrateKeyspace(storageKey) {
    try {
      var raw = localStorage.getItem(storageKey);
      if (!raw) return;
      var obj = JSON.parse(raw);
      if (!obj || typeof obj !== 'object') return;
      var changed = false;
      var wordToLesson = {};
      flat.forEach(function (it) { wordToLesson[it.word.toLowerCase()] = it.lessonId; });
      Object.keys(obj).forEach(function (key) {
        if (key.indexOf('ww:') !== 0) return;
        var parts = key.split('::');
        if (parts.length < 2) return;
        var wordPart = parts.slice(1).join('::').toLowerCase();
        var hitLesson = wordToLesson[wordPart];
        if (!hitLesson) return;
        var desiredKey = 'ww:' + hitLesson + '::' + wordPart;
        if (key !== desiredKey && !obj[desiredKey]) {
          obj[desiredKey] = obj[key];
          if (obj[desiredKey] && typeof obj[desiredKey] === 'object') {
            obj[desiredKey].categoryId = 'ww:' + hitLesson;
          }
          delete obj[key];
          changed = true;
        }
      });
      if (changed) localStorage.setItem(storageKey, JSON.stringify(obj));
    } catch (e) { /* ignore */ }
  })('vocab_quiz_word_stats');

  window.WW3000_BOOKS = books;
  window.WW3000_LESSONS = lessons;
  window.WW3000_WORDS = flat;
})();
`;

writeFileSync(OUTPUT, body);

let total = 0;
const perBook = {};
for (const b of books) {
  let n = 0;
  for (const ls of b.lessons) n += ls.items.length;
  perBook[b.label] = n;
  total += n;
}
console.log(`Emit done -> ${OUTPUT}`);
console.log(`Books: ${books.length}, total words: ${total}, dropped (no Cn at all): ${dropped}`);
if (droppedSamples.length) console.log('dropped samples:', droppedSamples);
console.log('per-book:', perBook);
