#!/usr/bin/env node
// 06-emit.mjs
// Combine by-category.json + ai-cache.json into vocabulary-quiz/life-basics-data.js.
// Words without a Chinese definition in cache are skipped (keeps data clean).
// Appends a slashed-id migration block so old slashed records map to new ids.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CLEAN = join(__dirname, '..', 'data', 'clean');
const OUTPUT = join(__dirname, '..', '..', '..', 'vocabulary-quiz', 'life-basics-data.js');

const { categories, buckets } = JSON.parse(readFileSync(join(CLEAN, 'by-category.json'), 'utf8'));
const cache = existsSync(join(CLEAN, 'ai-cache.json'))
  ? JSON.parse(readFileSync(join(CLEAN, 'ai-cache.json'), 'utf8'))
  : {};

function jsString(s) {
  return JSON.stringify(s == null ? '' : String(s));
}

function bestSubcategory(w) {
  // Prefer imsky topic suffix (after slash) when available
  if (w.imskyTopics && w.imskyTopics.length) {
    const t = w.imskyTopics[0].split('/').pop();
    return t.replace(/_/g, ' ');
  }
  if (w.yleTopics && w.yleTopics.length) {
    return w.yleTopics[0].replace(/_/g, ' ');
  }
  if (w._manual) return 'curated';
  return '';
}

const finalCategories = [];
let dropped = 0;
for (const cat of categories) {
  const items = [];
  for (const w of buckets[cat.id]) {
    const ai = cache[w.word];
    if (!ai || !ai.definitionCn) { dropped++; continue; }
    const pos = ai.partOfSpeech || (w.contentPos && w.contentPos[0]) || (w.pos && w.pos[0]) || '';
    items.push({
      word: w.word,
      pos,
      phonetic: ai.phonetic || w.phon_us || w.phon_br || '',
      definitionCn: ai.definitionCn,
      definitionEn: ai.definitionEn || w.oxfordDef || '',
      subcategory: bestSubcategory(w),
      source: w._manual ? 'Curated daily-life pin' : `${(w.sources || []).join('+') || 'pipeline'}`,
    });
  }
  finalCategories.push({
    id: cat.id,
    name: cat.name,
    description: cat.description,
    items,
  });
}

// Generate the JS file
const header = `// Life Basics vocabulary — generated by tools/life-vocab-pipeline/06-emit.mjs
// Sources: imsky/wordlists, ozbonus/yle-vocabulary-dataset, winterdl/oxford-5000, brucewlee/COCA + curated pins.
// AI-enhanced via enhanceBatch (Gemini). DO NOT edit by hand; rerun the pipeline instead.
(function () {
  function w(word, pos, cn, en, sub, source, phon) {
    return { word: word, pos: pos, phonetic: phon || '', definitionCn: cn, definitionEn: en, subcategory: sub || '', source: source || 'Life Basics rebuilt pipeline' };
  }

  var categories = [
`;

let body = '';
for (const cat of finalCategories) {
  body += `    {\n`;
  body += `      id: ${jsString(cat.id)},\n`;
  body += `      name: ${jsString(cat.name)},\n`;
  body += `      description: ${jsString(cat.description)},\n`;
  body += `      items: [\n`;
  cat.items.forEach((item, idx) => {
    const isLast = idx === cat.items.length - 1;
    body += `        w(${jsString(item.word)}, ${jsString(item.pos)}, ${jsString(item.definitionCn)}, ${jsString(item.definitionEn)}, ${jsString(item.subcategory)}, ${jsString(item.source)}, ${jsString(item.phonetic)})${isLast ? '' : ','}\n`;
  });
  body += `      ]\n    },\n`;
}
// remove trailing comma on last category
body = body.replace(/,\n$/, '\n');

const footer = `  ];

  var flat = [];
  categories.forEach(function (cat) {
    cat.items.forEach(function (item, idx) {
      flat.push(Object.assign({
        id: cat.id + '-' + (idx + 1),
        categoryId: cat.id,
        categoryName: cat.name,
        level: 'Life Basics Rebuilt'
      }, item));
    });
  });

  // ── Migration: old slashed records used different category ids and indexes.
  // Re-map them by word string so already-slashed items remain hidden.
  try {
    var SLASHED_KEY = 'life_basics_slashed';
    var raw = localStorage.getItem(SLASHED_KEY);
    if (raw) {
      var slashed = JSON.parse(raw);
      var changed = false;
      var byWord = {};
      flat.forEach(function (it) { byWord[it.word.toLowerCase()] = it; });
      Object.keys(slashed).forEach(function (oldId) {
        var rec = slashed[oldId];
        if (!rec) return;
        var hit = byWord[String(rec.word || '').toLowerCase()];
        if (!hit) return;
        if (oldId !== hit.id) {
          slashed[hit.id] = Object.assign({}, rec, {
            id: hit.id,
            categoryId: hit.categoryId,
            categoryName: hit.categoryName,
            definitionCn: hit.definitionCn,
            definitionEn: hit.definitionEn
          });
          delete slashed[oldId];
          changed = true;
        }
      });
      if (changed) localStorage.setItem(SLASHED_KEY, JSON.stringify(slashed));
    }
  } catch (e) { /* ignore */ }

  window.LIFE_BASICS_CATEGORIES = categories;
  window.LIFE_BASICS_WORDS = flat;
})();
`;

writeFileSync(OUTPUT, header + body + footer);

const totalWords = finalCategories.reduce((a, c) => a + c.items.length, 0);
console.log(`Emit done -> ${OUTPUT}`);
console.log(`Categories: ${finalCategories.length}, words: ${totalWords}, dropped (no Cn): ${dropped}`);
console.table(finalCategories.map(c => ({ id: c.id, words: c.items.length })));
