#!/usr/bin/env node
// 18-emit.mjs
// Combine by-category-hs.json + ai-cache.json into the v2 life-basics-data.js.
// Words without a Chinese definition in cache are skipped.
// Appends a slashed-id migration block (same as v1 emit) so old slashed
// records map onto the new ids by word string.
// Also appends a review-plan orphan logger so old plan rows that no longer
// match a current id stay alive but are flagged with a known fallback.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CLEAN = join(__dirname, '..', 'data', 'clean');
const OUTPUT = join(__dirname, '..', '..', '..', 'vocabulary-quiz', 'life-basics-data.js');

const { categories, buckets } = JSON.parse(readFileSync(join(CLEAN, 'by-category-hs.json'), 'utf8'));
const cache = existsSync(join(CLEAN, 'ai-cache.json'))
  ? JSON.parse(readFileSync(join(CLEAN, 'ai-cache.json'), 'utf8'))
  : {};

function jsString(s) {
  return JSON.stringify(s == null ? '' : String(s));
}

function bestSubcategory(w) {
  if (w.imskyTopics && w.imskyTopics.length) {
    const t = w.imskyTopics[0].split('/').pop();
    return t.replace(/_/g, ' ');
  }
  if (w.yleTopics && w.yleTopics.length) {
    return w.yleTopics[0].replace(/_/g, ' ');
  }
  if (w._manual) return 'curated';
  return '';
}

const finalCategories = [];
let dropped = 0;
const droppedSamples = [];
for (const cat of categories) {
  const items = [];
  const seen = new Set();
  for (const w of buckets[cat.id]) {
    if (seen.has(w.word)) continue;
    seen.add(w.word);
    const ai = cache[w.word];
    if (!ai || !ai.definitionCn) {
      dropped++;
      if (droppedSamples.length < 25) droppedSamples.push(w.word);
      continue;
    }
    const pos = ai.partOfSpeech || (w.contentPos && w.contentPos[0]) || (w.pos && w.pos[0]) || '';
    items.push({
      word: w.word,
      pos,
      phonetic: ai.phonetic || w.phon_us || w.phon_br || '',
      definitionCn: ai.definitionCn,
      definitionEn: ai.definitionEn || w.oxfordDef || '',
      subcategory: bestSubcategory(w),
      source: w._manual ? 'Curated HS daily-life pin' : `${(w.sources || []).join('+') || 'pipeline-v2'}`,
    });
  }
  finalCategories.push({
    id: cat.id,
    name: cat.name,
    description: cat.description,
    items,
  });
}

const header = `// Life Basics vocabulary v2 — generated by tools/life-vocab-pipeline/18-emit.mjs
// HS-level (CEFR B1-C1) with curated foundational pins.
// Sources: imsky/wordlists, ozbonus/yle-vocabulary-dataset, winterdl/oxford-5000,
// brucewlee/COCA, first20hours/google-10000-english, KyleBing/english-vocabulary SAT,
// lpmi-13 AWL (anti-filter) + curated HS pins.
// AI-enhanced via enhanceWord (Gemini). DO NOT edit by hand; rerun the pipeline instead.
(function () {
  function w(word, pos, cn, en, sub, source, phon) {
    return { word: word, pos: pos, phonetic: phon || '', definitionCn: cn, definitionEn: en, subcategory: sub || '', source: source || 'Life Basics v2 pipeline' };
  }

  var categories = [
`;

let body = '';
for (const cat of finalCategories) {
  body += `    {\n`;
  body += `      id: ${jsString(cat.id)},\n`;
  body += `      name: ${jsString(cat.name)},\n`;
  body += `      description: ${jsString(cat.description)},\n`;
  body += `      items: [\n`;
  cat.items.forEach((item, idx) => {
    const isLast = idx === cat.items.length - 1;
    body += `        w(${jsString(item.word)}, ${jsString(item.pos)}, ${jsString(item.definitionCn)}, ${jsString(item.definitionEn)}, ${jsString(item.subcategory)}, ${jsString(item.source)}, ${jsString(item.phonetic)})${isLast ? '' : ','}\n`;
  });
  body += `      ]\n    },\n`;
}
body = body.replace(/,\n$/, '\n');

const footer = `  ];

  var flat = [];
  categories.forEach(function (cat) {
    cat.items.forEach(function (item, idx) {
      flat.push(Object.assign({
        id: cat.id + '-' + (idx + 1),
        categoryId: cat.id,
        categoryName: cat.name,
        level: 'Life Basics HS v2'
      }, item));
    });
  });

  // ── Migration A: old slashed records.
  // v1 and earlier used different category ids and indexes. Re-map by word string
  // so already-slashed items remain hidden.
  try {
    var SLASHED_KEY = 'life_basics_slashed';
    var raw = localStorage.getItem(SLASHED_KEY);
    if (raw) {
      var slashed = JSON.parse(raw);
      var changed = false;
      var byWord = {};
      flat.forEach(function (it) { byWord[it.word.toLowerCase()] = it; });
      Object.keys(slashed).forEach(function (oldId) {
        var rec = slashed[oldId];
        if (!rec) return;
        var hit = byWord[String(rec.word || '').toLowerCase()];
        if (!hit) return;
        if (oldId !== hit.id) {
          slashed[hit.id] = Object.assign({}, rec, {
            id: hit.id,
            categoryId: hit.categoryId,
            categoryName: hit.categoryName,
            definitionCn: hit.definitionCn,
            definitionEn: hit.definitionEn
          });
          delete slashed[oldId];
          changed = true;
        }
      });
      if (changed) localStorage.setItem(SLASHED_KEY, JSON.stringify(slashed));
    }
  } catch (e) { /* ignore */ }

  // ── Migration B: review plan + word stats rows.
  // recordWordResult uses key "life:<categoryId>::<word>". When a word moves
  // to a different v2 category id, rewrite the key so FSRS scheduling and the
  // category filter both keep working. Plain orphans (word no longer in any
  // category) are left untouched so the user can still finish them.
  (function migrateKeyspace(storageKey) {
    try {
      var raw = localStorage.getItem(storageKey);
      if (!raw) return;
      var obj = JSON.parse(raw);
      if (!obj || typeof obj !== 'object') return;
      var changed = false;
      var wordToCat = {};
      flat.forEach(function (it) { wordToCat[it.word.toLowerCase()] = it.categoryId; });
      Object.keys(obj).forEach(function (key) {
        if (key.indexOf('life:') !== 0) return;
        var parts = key.split('::');
        if (parts.length < 2) return;
        var wordPart = parts.slice(1).join('::').toLowerCase();
        var hitCat = wordToCat[wordPart];
        if (!hitCat) return;
        var desiredKey = 'life:' + hitCat + '::' + wordPart;
        if (key !== desiredKey && !obj[desiredKey]) {
          obj[desiredKey] = obj[key];
          if (obj[desiredKey] && typeof obj[desiredKey] === 'object') {
            obj[desiredKey].categoryId = 'life:' + hitCat;
          }
          delete obj[key];
          changed = true;
        }
      });
      if (changed) localStorage.setItem(storageKey, JSON.stringify(obj));
    } catch (e) { /* ignore */ }
  })('vocab_quiz_review_plan');

  (function migrateKeyspace(storageKey) {
    try {
      var raw = localStorage.getItem(storageKey);
      if (!raw) return;
      var obj = JSON.parse(raw);
      if (!obj || typeof obj !== 'object') return;
      var changed = false;
      var wordToCat = {};
      flat.forEach(function (it) { wordToCat[it.word.toLowerCase()] = it.categoryId; });
      Object.keys(obj).forEach(function (key) {
        if (key.indexOf('life:') !== 0) return;
        var parts = key.split('::');
        if (parts.length < 2) return;
        var wordPart = parts.slice(1).join('::').toLowerCase();
        var hitCat = wordToCat[wordPart];
        if (!hitCat) return;
        var desiredKey = 'life:' + hitCat + '::' + wordPart;
        if (key !== desiredKey && !obj[desiredKey]) {
          obj[desiredKey] = obj[key];
          if (obj[desiredKey] && typeof obj[desiredKey] === 'object') {
            obj[desiredKey].categoryId = 'life:' + hitCat;
          }
          delete obj[key];
          changed = true;
        }
      });
      if (changed) localStorage.setItem(storageKey, JSON.stringify(obj));
    } catch (e) { /* ignore */ }
  })('vocab_quiz_word_stats');

  window.LIFE_BASICS_CATEGORIES = categories;
  window.LIFE_BASICS_WORDS = flat;
})();
`;

writeFileSync(OUTPUT, header + body + footer);

const totalWords = finalCategories.reduce((a, c) => a + c.items.length, 0);
console.log(`Emit done -> ${OUTPUT}`);
console.log(`Categories: ${finalCategories.length}, words: ${totalWords}, dropped (no Cn): ${dropped}`);
if (droppedSamples.length) console.log('dropped samples:', droppedSamples);
console.table(finalCategories.map(c => ({ id: c.id, words: c.items.length })));
